---
title: "JAGS"
author: "Jordan Aron"
date: "September 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rjags)
library(runjags)
library(modeest)
```

```{r}
N <- 1000
x <- rnorm(N, 0, 5)
 
write.table(x,
            file = 'example1.data',
            row.names = FALSE,
            col.names = FALSE)

```


```{r}
library('rjags')
 
jags <- jags.model('example1.bug',
                   data = list('x' = x,
                               'N' = N),
                   n.chains = 4,
                   n.adapt = 100)
 
update(jags, 1000)
 
jags.samples(jags,
             c('mu', 'tau'),
             1000)

```

```{r}
a <- jags(model.file = 'example1.bug',
                   data = list('x' = x,
                               'N' = N),
                   n.chains = 4, parameters.to.save = c('mu','tau'))
```


```{r}
N <- 1000
x <- 1:N
epsilon <- rnorm(N, 0, 1)
y <- x + epsilon
 
write.table(data.frame(X = x, Y = y, Epsilon = epsilon),
            file = 'example2.data',
            row.names = FALSE,
            col.names = TRUE)

```

```{r}

library('rjags')
 
jags <- jags.model('example2.bug',
                   data = list('x' = x,
                               'y' = y,
                               'N' = N),
                   n.chains = 4,
                   n.adapt = 100)
 
update(jags, 1000)
 
jags.samples(jags,
             c('a', 'b'),
             1000)

```

Implimenting gibbs for exponential 

```{r}
N <- 1000
x <- rbinom(N,1,.6)

write.table(x,
            file = 'example3.txt',
            row.names = FALSE,
            col.names = FALSE)
```

```{r}
library('rjags')
library('R2jags')
 
jags <- jags.model('example3.bug',
                   data = list('x' = x,
                               'N' = N),
                   n.chains = 4,
                   n.adapt = 100)
 
update(jags, 1000)
 
a<- jags(jags,
             c('p'),
             1000)

```

```{r}
a <- jags(model.file = 'example3.bug',
                   data = list('x' = x,
                               'N' = N),
                   n.chains = 4, parameters.to.save = 'p')
mcmcplot(a)
```



