---
title: "jagsv2"
author: "Jordan Aron"
date: "October 5, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
N <- 100000


x <- numeric(N)
for (i in 1:N){
  if (i%%2 == 0) {
    x[i] <- rnorm(1,0,10)
  } else  {
    x[i] <- rnorm(1,50,10)
  }
  
}

#plot(density(x))

```

```{r}
library('rjags')
 
jags <- jags.model('example4.bug',
                   data = list('x' = x,
                               'N' = N),
                   n.chains = 1,
                   n.adapt = 100)
 
update(jags, N)
 
#jags.samples(jags,
#             c('mu1','mu2', 'tau', ),
#             N)
smpls <- coda.samples(jags, c('mu1','mu2','tau', 'p'), 50)
plot(smpls)
```




Gibbs sampler entirely in R
```{r}
#mu1 mu2 sigma1 sigma2 p z x 
trials <- 10000
simlist <- matrix (rep(0,7*trials), ncol = 7)
simlist[1,5] <- runif(1)
ybar1 <- 0
ybar2 <- 50
for (i in 2:trials){
  simlist[i,1] <- rnorm(1, ybar1, 10)
  simlist[i,2] <- rnorm(1, ybar2, 10)


  #simlist[i,5] <- runif(1)
  if (i < 500){
    simlist[i,5] <- runif(1)
  } else {
    simlist[i,5] <- mean(simlist[1:i-1,6])
  }
  simlist[i,6] <- rbinom(1,1,simlist[i,5])
  if (simlist[i,6] == 1){
    simlist[i,7] <- rnorm(1,simlist[i,1],10)
  } else {
    simlist[i,7] <- rnorm(1,simlist[i,2],10)
  }
}
```